### PR TITLE
Change donation status endpoint

### PR DESCRIPTION
**Pull request by S3veria**
### What's new
**New endpoint:**
`localhost:3001/donation/changeStatus`
This endpoint is meant to be used to change the status (estado) for all the donations from a user to a campaign. We will update the state of all those donations to what `body.newState` is set to (see below for clarification).

**Changes in files:**
- added /campaignDonations/changeStatus route in donation.routes.js
- added userDonationStatusChange method to donation.controller.js
- added changeUserDonationStatus method to DonationClass.js

### How to use the endpoint
We want to change the state of the donations that a given user made towards a certain campaign, so, when we call this endpoint, we need to pass in the following parameters in the body of the request:
- userId: The id of the user whose donations we will be changing
- campaignId: The id of the campaign that has been assigned the donations
- newState: The state we want to set the donations to

**Here is what the body would look like (using test data):**
```
{
	"userId":"pysiNsIu8vhMeLK96bVTyYOnHNI3",
	"campaignId":"NcbSs5ml72TqTpg26Kzc",
	"newState":"completado"
}
```

The update will be reflected in firestore, but the endpoint will return the donations (An array of donations) of the user to that campaign with the new state, which looks like this:
```
[
	{
		"userId": "pysiNsIu8vhMeLK96bVTyYOnHNI3",
		"cantidad": 3,
		"estado": "completado",
		"producto": "Camisas Polo",
		"medida": "Unidades",
		"campaignId": "NcbSs5ml72TqTpg26Kzc"
	},
	{
		"medida": "Kg",
		"campaignId": "NcbSs5ml72TqTpg26Kzc",
		"producto": "Mangos",
		"userId": "pysiNsIu8vhMeLK96bVTyYOnHNI3",
		"estado": "completado",
		"cantidad": 7
	},
	{
		"medida": "Unidades",
		"cantidad": 2,
		"estado": "completado",
		"campaignId": "NcbSs5ml72TqTpg26Kzc",
		"producto": "Magic keyboards",
		"userId": "pysiNsIu8vhMeLK96bVTyYOnHNI3"
	}
]
```

### CODE REVIEW

**Review by J35HN — APPROVED** [review]
Chidussssssss

**Review by emiliogonmar2002 — CHANGES_REQUESTED** [review]
Solve conflicts

**Comment by S3veria** [comment]
> Solve conflicts

Listo! :D

**Review by emiliogonmar2002 — APPROVED** [review]
lgtm!

**Pull request merged**
